#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

bindkey -M viins "^W"   backward-kill-word
bindkey -M viins "^A"   beginning-of-line
bindkey -M viins "^E"   end-of-line
bindkey -M viins "[B"   history-search-forward               # down arrow
bindkey -M viins "[A"   history-search-backward              # up arrow
bindkey -M viins "^R"   history-incremental-search-backward  # ctrl-r

autoload -U bashcompinit && bashcompinit

eval "$(register-python-argcomplete linsharecli)"
eval "$(register-python-argcomplete linshareadmcli)"

# Centieme de secondes
export KEYTIMEOUT=10
alias tma="tmux att"

alias cddev="cd /home/fred/virtualenvs"
eval "$(register-python-argcomplete linsharecli)"
eval "$(register-python-argcomplete argtoolboxtool)"
export EDITOR=vim
eval "$(register-python-argcomplete sample.py)"
eval "$(register-python-argcomplete ./sample.py)"
eval "$(register-python-argcomplete linshareadmcli)"
eval "$(register-python-argcomplete ./svcdirectory.py)"
eval "$(register-python-argcomplete svcdirectory.py)"
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh


export TIMEFMT=$'\n%E real,\t%U user,\t%S sys'

